### ISSUE TITLE
ReferenceError: reactRoutesConfig is not defined

### ISSUE THREAD

**Issue by adamvaul** [Offroadcode/Umbraco-React-Starter-kit#1]
ReferenceError: reactRoutesConfig is not defined

Steps to Reproduce:
1.  Download fresh copy of the code.
2.  Running in Visual Studio 2013 Premium by clicking Debug > Start Without Debugging.

Server Error in '/' Application.

ReferenceError: reactRoutesConfig is not defined
   at Script Document:1:13 -> Router.run( reactRoutesConfig, '/', function( Handler ) {

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: ReferenceError: reactRoutesConfig is not defined
   at Script Document:1:13 -> Router.run( reactRoutesConfig, '/', function( Handler ) { 

Source Error: 

Line 13: </head>
Line 14: <body>
Line 15:     @Html.Render("reactApp", new {model= (object)model})
Line 16:  
Line 17:     @Html.RenderReactAssets()

Source File: c:\Adam\Sample Projects\Umbraco-React-Starter-kit-master2\Orc.ReactExample\Views\ReactRenderedPage.cshtml    Line: 15 

Stack Trace: 

[Exception: ReferenceError: reactRoutesConfig is not defined
    at Script Document:1:13 -> Router.run( reactRoutesConfig, '/', function( Handler ) { ]
   Orc.SuperchargedReact.Core.ReactRunner.Execute(String containerId, String url, String encodedProps, String& inBrowserScript, ReactPerformaceMeasurements& measurements) +1073
   Orc.SuperchargedReact.Web.ReactHtmlExtensions.Render(HtmlHelper helper, String containerId, Object props) +117
   ASP._Page_Views_ReactRenderedPage_cshtml.Execute() in c:\Adam\Sample Projects\Umbraco-React-Starter-kit-master2\Orc.ReactExample\Views\ReactRenderedPage.cshtml:15
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +96
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +76
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +259
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +115
   Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) +93
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +294
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17() +23
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +242
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +21
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +242
   System.Web.Mvc.<>c__DisplayClass1c.<InvokeActionResultWithFilters>b__19() +21
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +175
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +89
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +102
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +57
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +43
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +14
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +62
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +57
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +62
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +47
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +25
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +23
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +62
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +47
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9690172
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by PeteDuncanson** [comment]
This should be fixed by https://github.com/Offroadcode/SuperchargedReact.Net/pull/4 if you want to give it another go, you might need to update the DLL's. I'll try to get that done asap.
